import type { Fair } from "@/types";

// Shown only when a fair IS active but the DB fetch fails — never on
// the between-fairs page. Kept here so page.tsx stays clean and the
// preview data is reusable.
export const FALLBACK_FAIR: Fair = {
  id: "preview",
  name: "IAES U.S. University Education Fair — August 2026",
  city: "Ahmedabad",
  venue: "Ahmedabad (Venue TBC)",
  fair_date: "2026-08-06",
  fair_date_start: "2026-08-06",
  fair_date_end: "2026-08-08",
  arrive_by: "2026-08-05",
  depart_after: "2026-08-09",
  registration_deadline: "2026-07-05",
  booth_price_usd: 1700,
  price_standard_usd: 1700,
  price_standard_inr: 161500,
  price_earlybird_usd: 1500,
  price_earlybird_inr: 142500,
  earlybird_deadline: "2026-06-15",
  max_universities: 30,
  includes: [
    "Travel to institute visits by cabs arranged by IAES",
    "Logistics and lunch during all days",
  ],
  description:
    "IAES Ahmedabad organizes an open U.S. University Education Fair along with institutional visits across Gujarat. Expected 1000+ student attendees over 3 days.",
  is_active: true,
  status: "PUBLISHED",
  created_at: new Date().toISOString(),
  itinerary: [
    {
      id: "preview-1",
      fair_id: "preview",
      day_number: 1,
      event_date: "2026-08-06",
      event_type: "CAMPUS_VISIT",
      institution_name: "IIT Gandhinagar",
      venue_name: "Academic Block",
      city: "Gandhinagar",
      address: null,
      start_time: "10:00",
      end_time: "13:00",
      is_main_fair: false,
      is_confirmed: true,
      is_public: true,
      notes: "Lunch provided by IAES.",
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "preview-2",
      fair_id: "preview",
      day_number: 2,
      event_date: "2026-08-07",
      event_type: "CAMPUS_VISIT",
      institution_name: "Nirma University",
      venue_name: "Conference Centre",
      city: "Ahmedabad",
      address: null,
      start_time: "10:00",
      end_time: "13:00",
      is_main_fair: false,
      is_confirmed: false,
      is_public: true,
      notes: null,
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "preview-3",
      fair_id: "preview",
      day_number: 3,
      event_date: "2026-08-08",
      event_type: "OPEN_FAIR",
      institution_name: null,
      venue_name: "Hotel Courtyard by Marriott",
      city: "Ahmedabad",
      address: null,
      start_time: "18:00",
      end_time: "21:00",
      is_main_fair: true,
      is_confirmed: true,
      is_public: true,
      notes: "Smart/formal dress recommended.",
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
